services:
  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  api:
    build:
      context: ./server
    container_name: media-pipeline-api
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env

volumes:
  redis-data:
